### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/f5-digital-customer-engagement-center#19]
.github/workflows/gitleaks.yml

```yaml
---
name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform-docs
        run: |
          sudo curl -sLo /usr/local/bin/terraform-docs https://github.com/segmentio/terraform-docs/releases/download/v0.10.1/terraform-docs-v0.10.1-linux-amd64
          sudo chmod 0755 /usr/local/bin/terraform-docs
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
```
